const d = new Date();
console.log(d.getFullYear(), "<==Get the year as a four digit number (yyyy)")
console.log(d.getMonth(),"<==Get the month as a number (0-11)")
console.log(d.getDate(),"<==Get the  day as a number (1-31)")
console.log(d.getHours(),"<==Get the hour (0-23)")
console.log(d.getMinutes(),"<==Get the minute (0-59)")
console.log(d.getSeconds()," <==Get the second (0-59)")
console.log(d.getMilliseconds(),"<==Get the millisecond (0-999)")
console.log(d.getTime(),"<==Get the time (milliseconds since January 1, 1970)")
console.log(d.getDay(),"<==Get the weekday as a number (0-6)")
// d.Date.now()
console.log(String(d))
console.log(d.getUTCFullYear(), "<==Get UTC the year as a four digit number (yyyy)")
console.log(d.getUTCMonth(),"<==Get UTC the month as a number (0-11)")
console.log(d.getUTCDate(),"<==Get UTC the utc day as a number (1-31)")
console.log(d.getUTCHours(),"<==Get UTC the hour (0-23)")
console.log(d.getUTCMinutes(),"<==Get  UTC the minute (0-59)")
console.log(d.getUTCSeconds()," <==Get UTC the second (0-59)")
console.log(d.getUTCMilliseconds(),"<==Get UTC the millisecond (0-999)")
console.log(d.getUTCDay(),"<==Get the weekday as a number (0-6)")